SNT\GestionEmployerBundle\Entity\Service:
    type: entity
    table: Service
    id:
        idservice:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idService
            generator:
                strategy: IDENTITY
    fields:
        nomservice:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: nomService
    lifecycleCallbacks: {  }
